### ISSUE TITLE
Debug UE4.26 with VSCode not working

### ISSUE THREAD

**Issue by jokance** [botman99/ue4-xcode-vscode-mac#3]
Hi, my MacBook Air M1 can't debug UE4.26 with vscode, when I click green RUN button, it show me this warning in second image, do you know why?
<img width="1440" alt="截屏2021-01-02 下午8 42 36" src="https://user-images.githubusercontent.com/7630331/103457544-37d44700-4d3b-11eb-9e49-e34d4552f22d.png">
<img width="1552" alt="截屏2021-01-02 下午8 37 34" src="https://user-images.githubusercontent.com/7630331/103457556-4b7fad80-4d3b-11eb-9c5a-3b6cb4481b9d.png">

**Comment by botman99** [comment]
Searching on google for "process resume at entry point failed" shows results like this...

https://github.com/vadimcn/vscode-lldb/issues/397

...indicating that vscode lldb debugger doesn't support Apple's M1 silicon chip yet.  You'll have to wait until vscode is updated to support the M1 chip.

**Comment by jokance** [comment]
Got it!
