### ISSUE TITLE
can not go to reference

### ISSUE THREAD

**Issue by ht15** [botman99/ue4-xcode-vscode-mac#5]
![image](https://user-images.githubusercontent.com/26128364/109382263-683ef880-791a-11eb-9898-848fae6d5cd9.png)
can not go to reference smoothly

**Comment by botman99** [comment]
I usually disable Intellisense for this reason.  I haven't played around with trying to get Intellisense to work properly with VSCode, but you might try looking at the following github document or watching this YouTube video...

https://gist.github.com/boocs/31e6c2e54815b7ba6246ee20315acf96

https://www.youtube.com/watch?v=yAUgFZh28aA

**Comment by ht15** [comment]
thanks a lot. I have follow it in my MACOS, but GENERATED_BODY() cann't get intellisense rightly yet.
