### ISSUE TITLE
Incorrect instructions about using quotes in file path

### ISSUE THREAD

**Issue by JoeStrout** [botman99/ue4-xcode-vscode-mac#7]
The section on setting up VS Code says:

> ..then run the following command (using the full path to your .uproject file):
> 
> ./GenerateProjectFiles.sh -project="/Users/<username>/Documents/Unreal\ Projects/TPGame/TPGame.uproject" -game -vscode
> 
> Make SURE to place double quotes around the full path to the .project file after the "-project=" argument so that spaces in the path name are preserved.

But this does not work as shown, because the space in the path is already backslash-escaped.  The quotation marks cause this to be treated as a literal backslash, rather than as a space character.  You need to either quote the path and not include the backslash, or include the backslash and omit the quotes.

I ran into this exact problem (my space character was escaped because I dragged the folder into Terminal from the Finder), and following the instructions, I made SURE to use double quotes... it took me quite a while to notice the problem.  So please clarify these instructions to point out that you need quotes OR escaped spaces, but not both.

**Comment by botman99** [comment]
Ah, yes.  Good catch.  I think that was copy/pasted from the Windows commands I had.  You're, right about the double quotes not being needed if you escape the space with a backslash.  I'll fix it up.

**Comment by botman99** [comment]
Fixed in [050a9d1f749406c4933c1deb6dbaa2e0d7650b17](https://github.com/botman99/ue4-xcode-vscode-mac/commit/050a9d1f749406c4933c1deb6dbaa2e0d7650b17).
