### ISSUE TITLE
Issues with iOS device testing

### ISSUE THREAD

**Issue by joelkandiah** [botman99/ue4-xcode-vscode-mac#9]
Following the advice of the walkthrough I managed to get the C++ code to run, however this suggests installing an older version of Xcode for UE 4.26.2, this however conflicts with the requirement of a newer version of Xcode required to test the iOS code on device. Considering I had that worling before but not the C++ code, is there any advice on whether following this tutorial and then updating xcode, whilst maintaining the C++ code?

**Comment by botman99** [comment]
I haven't actually depoyed for iOS.  I would suggest updating to UE 4.27 and update macOS (if required) to be able install and use newer Xcode.

**Comment by joelkandiah** [comment]
Thanks for your help. No worries, I'm part of a team so can't make that decision unilaterally so will try and find another solution or move the project with the team to the newer version.
